dist: trusty

jobs:
  include:
    - stage: unit test
      script:
        - npm run test:unit
    - stage: cypress test
      script:
        - npm run build:run:cypress
    - stage: build docker image and publish
      script:
        - npm run build:prod
        - npm run docker:login
        - npm run publish:image
