version: '3.5'

services:
  app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    networks:
      - lunch_app
networks:
  lunch_app: