version: '3.2'

services:
  test:
    container_name: react-app-test
    build:
      context: .
      dockerfile: Dockerfile_test
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - CI=true
    command: npm test