version: '3.2'

# run Cypress tests and exit with command
#   docker-compose up --exit-code-from cypress
services:
  # this is the web application we are going to test
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile_cypress
    restart: always
    ports:
      - "3000:80"
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    depends_on:
      - frontend
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://frontend:80
      - CYPRESS_domain=lunchmenuapp.eu.auth0.com
      - CYPRESS_clientId=ZOiGpF4Ne7KWbJCCC0lF6vqSWeC4Z2W6
      - CYPRESS_audience=https://lunchmenuapp/api
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e